# Custom Language File for Launcher Customizer

[ejs.app]
title = "LSN RP"

[ejs.landing]
mediaGitHubURL = "https://github.com/xana/XanaLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/9Jetj6nEJb"

[ejs.settings]
sourceGithubLink = "https://github.com/xana802/XanaLauncher"
supportLink = "https://github.com/xana802/XanaLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenu"
welcomeDescription = "Ceci est le launcheur pour le serveur lsn."
welcomeDescCTA = ""
